version: "3.9"

services:

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgres_sovkombank
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=exchange
