# Generated by Django 4.1.3 on 2022-11-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acc',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='acc',
            new_name='acc_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='user_id',
        ),
    ]
