# Generated by Django 4.1.3 on 2022-11-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_user_id_acc_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='amount_in_acc',
            field=models.IntegerField(default=0, verbose_name='Сумма на счете'),
        ),
    ]
