# Generated by Django 4.1.3 on 2022-11-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_acc_amount_in_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='amount_in_acc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма на счете'),
        ),
    ]
