# Generated by Django 4.1.3 on 2022-11-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='user_id',
        ),
    ]
