# Generated by Django 4.1.3 on 2022-11-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_document_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user_id',
            new_name='user',
        ),
    ]
